import java.sql.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        String jdbcUrl = "jdbc:mysql://localhost/?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
        String username = "root";
        String password = "admin";

        Connection con = null;
        Statement s = null;
        
        try { 
            Class.forName("com.mysql.cj.jdbc.Driver")  ;

            con = DriverManager.getConnection(jdbcUrl, username, password);
            con.setAutoCommit(false);

            PreparedStatement statement = null;
            statement = con.prepareStatement("DROP DATABASE IF EXISTS bikesharing");
            statement.execute();
            
            statement = con.prepareStatement("CREATE DATABASE bikesharing");

            statement.execute();
            System.out.println("Database created successfully");

            statement = con.prepareStatement("USE bikesharing");
            statement.execute();
            System.out.println("Using bikesharing db");

            statement = con.prepareStatement(
                        "CREATE TABLE IF NOT EXISTS nyc( " +
                        "rideId INTEGER not NULL, " +
                        "bikeId INTEGER not NULL, " +
                        "startTime DATETIME, " +
                        "endTime DATETIME, " +
                        "startStation INTEGER, " +
                        "endStation INTEGER, " +
                        "subscriber BOOLEAN, " +
                        "PRIMARY KEY (rideId))");
            statement.execute();
            System.out.println("nyc table created");
            
            statement = con.prepareStatement(
                        "CREATE TABLE IF NOT EXISTS dc( " +
                        "rideId INTEGER not NULL, " + 
                        "bikeId INTEGER not NULL, " + 
                        "startTime DATETIME, " + 
                        "endTime DATETIME, " + 
                        "startStation INTEGER, " + 
                        "endStation INTEGER, " + 
                        "subscriber BOOLEAN, " +
                        "PRIMARY KEY (rideId))");
            statement.execute();
            System.out.println("dc table created");

            statement = con.prepareStatement(
                        "CREATE TABLE IF NOT EXISTS chicago( " +
                        "rideId INTEGER not NULL, " + 
                        "bikeId INTEGER not NULL, " + 
                        "startTime DATETIME, " + 
                        "endTime DATETIME, " + 
                        "startStation INTEGER, " + 
                        "endStation INTEGER, " + 
                        "subscriber BOOLEAN, " +
                        "PRIMARY KEY (rideId))");
            statement.execute();
            System.out.println("chicago table created");


        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (s != null) {
                    s.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
